version: "3.8"


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
        ADMINER_DEFAULT_SEVERAL: db

  proxxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '8090:81'
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt

  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
    ports:
      - "8000:8000"
    depends_on:
      - db
        #nginx:
       #image: nginx:latest
       #ports:
      # - "80:80"
        #- "443:443"
        #volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf
      #command: /bin/sh -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      #depends_on:
      #- frontend
      #- backend

volumes:
  db_data:
